#!/usr/bin/env ruby

# Runs testing traces.

ROOT = File.dirname(__FILE__)
CONN = ROOT + '/conn/'

Dir.mkdir CONN unless File.directory? CONN

class MotMot
  attr_accessor :conn, :stdin
  def initialize connect, screen=true
    @conn = CONN + (rand(999999) + 1).to_s
    system "mkfifo #{@conn}in"
    system "screen #{ROOT}/motmot #{@conn} #{connect.join ' '}"
    @stdin = open @conn + 'in', 'a'
    @stdin.sync = true
  end
end

motmots = Hash.new

Signal.trap "INT" do
  puts "Terminating..."
  exit 0
end

f = (ARGV[0] == '-' or ARGV[0].nil?) ? $stdin : open(ARGV[0], 'r')

begin
  loop do
    case f.readline
    when /> run (\S+)(\s.*|)/ then
      others = $2.strip.split.map { |k| motmots[k] }
      motmots[$1] = MotMot.new(others.map(&:conn), ENV['SILENT'].nil?)
      sleep 1
    when /([^ ]+): \/invite (\S+)/ then
      invited = motmots[$2].conn
      motmots[$1].stdin << "/invite " << invited << "\n"
    when /([^ ]+): (.*)/ then
      motmots[$1].stdin << $2.strip << "\n"
    end
    sleep 0.001
  end
rescue EOFError
  loop { sleep 1 }
end
