#
# Trill test binary Makefile.
#

MOTMOT_ROOT = ../..

all: trill plume

trill:
	$(MAKE) -C $(MOTMOT_ROOT) trill

plume:
	$(MAKE) -C $(MOTMOT_ROOT) plume

clean:
	$(MAKE) -C $(MOTMOT_ROOT) clean-trill
